<a href="https://colab.research.google.com/github/nedokormysh/Stepik_algorithms_ml_course/blob/linear_regression/ML_algorithms_2_1_linear_reg_dirty.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
import pandas as pd
import random
from sklearn.model_selection import train_test_split

In [12]:
from sklearn.datasets import make_regression

X_mk, y_mk = make_regression(n_samples=5, n_features=3, n_informative=10, noise=15, random_state=42)

# 2_1_5

Данный класс при инициализации должен принимать на вход два параметра:

n_iter — количество шагов градиентного спуска.

По-умолчанию: 100

learning_rate — коэффициент скорости обучения градиентного спуска.

По-умолчанию: 0.1

Все переданные (или дефолтные) параметры должны быть сохранены внутри класса.

При обращении к экземпляру класса (или при передачи его в функцию print) необходимо распечатать строку по следующему шаблону (строго в таком виде):


MyLineReg class: n_iter=<n_iter>, learning_rate=<learning_rate>

In [ ]:
class MyLineReg():
    def __init__(self, n_iter=100, learning_rate=1):
        self.n_iter = n_iter
        self.learning_rate = learning_rate

    def __repr__(self):
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

# 2_1_6

1) В инициализатор класса добавить новый параметр — weights — который будет хранить веса модели. По умолчанию он ничего не содержит.
2) Вам необходимо реализовать метод fit в Вашем классе. Данный метод должен делать следующее:
На вход принимать три атрибута:
- X — все фичи в виде датафрейма пандаса.
  Примечание: даже если фича будет всего одна это все равно будет датафрейм, а не серия.
- y — целевая переменная в виде пандасовской серии.
- verbose — указывает на какой итерации выводить лог. Например, значение 10 означает, что на каждой 10 итерации градиентного спуска будет печататься лог. Значение по умолчанию: False (т.е. ничего не выводится).
Дополнить переданную матрицу фичей единичным столбцом слева.
Определить сколько фичей передано и создать вектор весов, состоящий из одних единиц соответствующей длинны: т.е. количество фичей + 1.
Дальше в цикле (до n_iter):
- Предсказать $y^$​

- Посчитать ошибку (MSE)
- Вычислить градиент
- Сделать шаг размером learning rate в противоположную от градиента сторону
- Сохранить обновленные веса внутри класса
В процессе обучения необходимо выводить лог, в котором указывать номер итерации и значение функций потерь:
start | loss: 42027.65
100 | loss: 1222.87
200 | loss: 232.17
300 | loss: 202.4
где start - значении функции потерь до начала обучения. Далее выводится каждое i-ое значение итерации переданное в параметре verbose. Если verbose = False, то лог не выводится вовсе.
З.Ы. Данный вывод никак проверяться не будет. Он в основном нужен для отладки. Поэтому можете модифицировать его внешний вид под свои нужды.
Метод ничего не возвращает.
3) Необходимо реализовать метод get_coef, который будет возвращать значения весов в виде вектора NumPy, начиная со второго значения. Первое значение нам не нужно, потому что оно соответствует фиктивной фиче (единичке). Все же остальные могут использоваться для оценки важности фичей.
Проверка

Входные данные: несколько наборов параметров для линейной регрессии
Выходные данные: коэффициенты обученной линейной регрессии (их среднее)

## Добавление столбца единиц слева.

In [ ]:
X = np.random.uniform(size=(5, 3))
X

array([[0.70457135, 0.429959  , 0.26054683],
       [0.40852386, 0.88449507, 0.31293098],
       [0.70437775, 0.61764497, 0.65022736],
       [0.0955257 , 0.96940716, 0.12378805],
       [0.8671371 , 0.86211975, 0.1572261 ]])

In [ ]:
X.shape

(5, 3)

### numpy

In [ ]:
np.c_[np.ones(X.shape[0]), X]

array([[1.        , 0.70457135, 0.429959  , 0.26054683],
       [1.        , 0.40852386, 0.88449507, 0.31293098],
       [1.        , 0.70437775, 0.61764497, 0.65022736],
       [1.        , 0.0955257 , 0.96940716, 0.12378805],
       [1.        , 0.8671371 , 0.86211975, 0.1572261 ]])

### pandas

In [ ]:
X = np.random.uniform(size=(5, 3))
X = pd.DataFrame(X)
X

0         1         2
0  0.549973  0.158042  0.350349
1  0.730726  0.804798  0.691874
2  0.503351  0.906758  0.906255
3  0.183549  0.465526  0.249728
4  0.907699  0.529097  0.692194

In [ ]:
X.insert(loc=0, column='x_0', value=1)
X

x_0         0         1         2
0    1  0.549973  0.158042  0.350349
1    1  0.730726  0.804798  0.691874
2    1  0.503351  0.906758  0.906255
3    1  0.183549  0.465526  0.249728
4    1  0.907699  0.529097  0.692194

In [ ]:
X.shape[1]

4

In [ ]:
w = np.ones(X.shape[1])
w

array([1., 1., 1., 1.])

In [ ]:
w.shape[0]

4

## Реализация.

Делал реализацию через нампай. Но оказалось нужно через пандас.

In [ ]:
from sklearn.datasets import make_regression

X_mk, y_mk = make_regression(n_samples=2, n_features=3, n_informative=10, noise=15, random_state=42)

In [ ]:
X

x_0         0         1         2
0    1  0.549973  0.158042  0.350349
1    1  0.730726  0.804798  0.691874
2    1  0.503351  0.906758  0.906255
3    1  0.183549  0.465526  0.249728
4    1  0.907699  0.529097  0.692194

In [ ]:
X.to_numpy()

array([[1.        , 0.5499732 , 0.15804208, 0.35034939],
       [1.        , 0.73072586, 0.80479843, 0.69187437],
       [1.        , 0.50335082, 0.90675829, 0.90625535],
       [1.        , 0.18354927, 0.46552554, 0.24972843],
       [1.        , 0.90769903, 0.52909714, 0.69219378]])

### Pandas version

In [ ]:
# X = pd.DataFrame(X_mk)
# y = pd.Series(y_mk)
# X.columns = [f'col_{col}' for col in X.columns]


# class MyLineReg():
#     def __init__(self, n_iter=2, learning_rate=1, weights=None):
#         self.n_iter = n_iter
#         self.learning_rate = learning_rate
#         self.weights = weights

#     def __repr__(self):
#         return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

#     def fit(self, X, y, verbose=False):
#         X.insert(loc=0, column='x_0', value=1)
#         self.weights = np.ones(X.shape[1])
#         w = np.ones(X.shape[1])
#         print(w)

#         for i in range(self.n_iter):
#             y_tilda = X.dot(self.weights)
#             mse = ((y - y_tilda)**2) / y.shape[0]
#             print('y_t\n', y_tilda[0: 5])
#             print('y\n', y[0: 5])
#             print('mse\n', mse[0: 5])
#             nabla_mse = (2 / y.shape[0]) * mse.dot(X)
#             # print(nabla_mse)
#             w = w - self.learning_rate * nabla_mse
#             # print(w)
#             self.weights = w.values
#             print(self.weights)
#         # return mse

#     # def get_coef():
# reg = MyLineReg()
# mse = reg.fit(X, y)

In [ ]:
X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)
X.columns = [f'col_{col}' for col in X.columns]

class MyLineReg():
    def __init__(self, n_iter=50, learning_rate=0.01, weights=None):
        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights

    def __repr__(self):
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    def fit(self, X, y, verbose=False):
        X.insert(loc=0, column='x_0', value=1)
        w = np.ones(X.shape[1])

        for i in range(self.n_iter):
            y_tilda = np.dot(X, w)
            nabla_mse = (2 / y.shape[0]) * ((y_tilda - y)).dot(X)
            w -= self.learning_rate * nabla_mse

            if verbose != False and i % verbose == 0:
              err = np.mean((y - y_tilda)**2)
              print(f'i = {i} | loss = {err}')
            self.weights = w.to_numpy()
    def get_coef(self):
      return self.weights[1:]



reg = MyLineReg()
reg.fit(X, y, verbose=10)
c = reg.get_coef()
c

i = 0 | loss = 810.9197945296903
i = 10 | loss = 606.6150502834279
i = 20 | loss = 487.2410882189987
i = 30 | loss = 407.1121904869559
i = 40 | loss = 347.0692499463499


array([  0.29935983,  10.34644432,   2.16254471, -10.75406276])

##### Верное решение pandas.

In [ ]:
# правильное решение

class MyLineReg():
    def __init__(self, n_iter=50, learning_rate=0.01, weights=None):
        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights

    def __repr__(self):
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    def fit(self, X, y, verbose=False):
        X.insert(loc=0, column='x_0', value=1)
        w = np.ones(X.shape[1])

        for i in range(self.n_iter):
            y_tilda = np.dot(X, w)
            nabla_mse = (2 / y.shape[0]) * ((y_tilda - y)).dot(X)
            w -= self.learning_rate * nabla_mse

            if verbose != False and i % verbose == 0:
              err = np.mean((y - y_tilda)**2)
              print(f'i = {i} | loss = {err}')
            self.weights = w.to_numpy()
    def get_coef(self):
      return self.weights[1:]

In [ ]:
np.sum([1,	-0.234153,	1.523030,	-0.234137])
np.sum([1,	0.767435,	1.579213,	-0.469474])

2.877174

In [ ]:
# mse_x = mse

In [ ]:
# mse_x

In [ ]:
# mse_x.values

In [ ]:
# mse_x.dot(X)

In [ ]:
# X

In [ ]:
# X.mul(mse_x)

In [ ]:
# np.dot(mse_x, X)

### Numpy version

In [ ]:
X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)
X.columns = [f'col_{col}' for col in X.columns]

class MyLineReg():
    def __init__(self, n_iter=50, learning_rate=0.01, weights=None):
        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights

    def __repr__(self):
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    def fit(self, X, y, verbose=False):
        X.to_numpy()
        y.to_numpy()
        X = np.c_[np.ones(X.shape[0]), X]
        w = np.ones(X.shape[1])

        for i in range(self.n_iter):
            y_tilda = np.dot(X, w)
            # print(y_tilda)

            # print('y_t\n', y_tilda[0: 5])
            # print('y\n', y[0: 5])
            # print('y-y', (y_tilda - y))
            nabla_mse = (2 / y.shape[0]) * ((y_tilda - y)).dot(X)
            # print('nabla_mse = ', nabla_mse)
            w -= self.learning_rate * nabla_mse
            # print(verbose)
            # print(i % verbose)
            if verbose != False and i % verbose == 0:
              err = np.mean((y - y_tilda)**2)
              print(f'i = {i} | loss = {err}')

    def get_coef(self):
      return self.weights



reg = MyLineReg()
mse = reg.fit(X, y, verbose=10)

i = 0 | loss = 810.9197945296903
i = 10 | loss = 606.6150502834279
i = 20 | loss = 487.2410882189987
i = 30 | loss = 407.11219048695597
i = 40 | loss = 347.0692499463499


In [ ]:
X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)
X.columns = [f'col_{col}' for col in X.columns]

class MyLineReg():
    def __init__(self, n_iter=10, learning_rate=0.01, weights=None):
        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights

    def __repr__(self):
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    def fit(self, X, y, verbose=False):
        X.to_numpy()
        y.to_numpy()
        X = np.c_[np.ones(X.shape[0]), X]
        # print(X)
        w = np.ones(X.shape[1])

        for i in range(self.n_iter):
            y_tilda = np.dot(X, w)
            # print(y_tilda)
            err = np.mean((y - y_tilda)**2)
            print('err', err)
            # print('y_t\n', y_tilda[0: 5])
            # print('y\n', y[0: 5])
            # print('y-y', (y_tilda - y))
            nabla_mse = (2 / y.shape[0]) * ((y_tilda - y)).dot(X)
            # print('nabla_mse = ', nabla_mse)
            w -= self.learning_rate * nabla_mse

            print(w)
            # for k in range(len(W)):
            #     print(X[k])
                # W[k] -= self.learning_rate * ((2 / y.shape[0]) * np.sum(X[k] * (y_tilda - y)))

        #     # print(w)
        # # self.weights = w
        # # print(self.weights)
        # # return mse

    # # def get_coef():
reg = MyLineReg()
mse = reg.fit(X, y)

err 810.9197945296903
[0.83681081 1.20684179 1.05654835 0.55519368]
err 784.3136942324145
[0.68522456 1.41324185 1.11062721 0.12541128]
err 759.3965115754756
[ 0.54469836  1.61915866  1.16234536 -0.28997777]
err 736.0309942220578
[ 0.41471352  1.82455298  1.21180678 -0.69157645]
err 714.0916155375182
[ 0.29477443  2.02938773  1.25911087 -1.07996136]
err 693.4635643447316
[ 0.18440758  2.23362786  1.30435264 -1.45568388]
err 674.0418218386642
[ 0.08316054  2.43724031  1.34762291 -1.81927128]
err 655.7303181388013
[-0.00939891  2.6401939   1.38900849 -2.17122779]
err 638.4411616071235
[-0.09368375  2.84245923  1.42859238 -2.51203561]
err 622.0939346523971
[-0.1700885   3.0440086   1.46645388 -2.84215589]


In [ ]:
X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)
X.columns = [f'col_{col}' for col in X.columns]

# X.to_numpy()
# X = np.c_[np.ones(X.shape[0]), X]
# w = np.ones(X.shape[1])
# X.dot(w)


def calc_mse(y, y_pred):
    err = np.mean((y - y_pred)**2)
    return err

class MyLineReg():
    def __init__(self, n_iter=2, learning_rate=1, weights=None):
        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights

    def __repr__(self):
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    def calc_mse(y_pred, y_true):
      err = np.mean((y_true - y_pred)**2)
      return err


    def fit(self, X, y, verbose=False):
        X.to_numpy()
        y.to_numpy()
        X = np.c_[np.ones(X.shape[0]), X]
        w = np.ones(X.shape[1])
        W = np.ones(X.shape[1])
        # print(w)
        # print(X)

        for i in range(self.n_iter):
        #     # y_tilda = w.dot(X)
            y_tilda = np.dot(X, w)
            # print(y_tilda)
            # mse = np.mean((y - y_tilda)**2) #/ y.shape[0]
            mse = (y_tilda - y)**2
            err = calc_mse(y, y_tilda)
            print('mse', mse)
            # print('err', err)
            # print('y_t\n', y_tilda[0: 5])
            # print('y\n', y[0: 5])
            nabla_mse = (2 / y.shape[0]) * mse.dot(X)
            #     # print('nabla_mse = ', nabla_mse)
            w -= self.learning_rate * nabla_mse

            print(X[1])
            # for k in range(len(W)):
            #     print(X[k])
                # W[k] -= self.learning_rate * ((2 / y.shape[0]) * np.sum(X[k] * (y_tilda - y)))

        #     # print(w)
        # # self.weights = w
        # # print(self.weights)
        # # return mse

    # # def get_coef():
reg = MyLineReg()
mse = reg.fit(X, y)

mse 0    1256.143148
1     365.696441
dtype: float64
[ 1.          0.64768854 -0.1382643   0.49671415]
mse 0    2.372607e+07
1    7.247143e+06
dtype: float64
[ 1.          0.64768854 -0.1382643   0.49671415]


In [ ]:
X = np.array([[ 1.,         -0.23415337,  1.52302986, -0.23413696],
 [ 1.,          0.76743473,  1.57921282, -0.46947439],
 [ 1.,         -0.1382643,   0.49671415,  0.64768854]])

print(X.shape)

w = np.ones(X.shape[0])
w
# w = [1, 1, 1]
# np.dot(X, w)
np.dot(w, X)

(3, 4)


array([ 3.        ,  0.39501706,  3.59895683, -0.05592281])

In [ ]:
X = np.array([[1, 1, 1, 1],
              [1, 1, 2, 5],
              [1, 1, 2, 5]])
X
print(X.shape)

W = np.array([1, 1, 1])

# w = np.ones(X.shape[1])
np.dot(W, X)

(3, 4)


array([ 3,  3,  5, 11])

In [ ]:
X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)
X.columns = [f'col_{col}' for col in X.columns]

class MyLineReg():
    def __init__(self, n_iter=51, learning_rate=0.01, weights=None):
        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights

    def __repr__(self):
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    def fit(self, X, y, verbose=False):
        X.to_numpy()
        y.to_numpy()
        X = np.c_[np.ones(X.shape[0]), X]
        w = np.ones(X.shape[1])

        for i in range(self.n_iter):
            y_tilda = np.dot(X, w)
            nabla_mse = (2 / y.shape[0]) * ((y_tilda - y)).dot(X)
            w -= self.learning_rate * nabla_mse

            if verbose != False and i % verbose == 0:
              err = np.mean((y - y_tilda)**2)
              print(f'i = {i} | loss = {err}')

            self.weights = w

    def get_coef(self):
      return self.weights



reg = MyLineReg()
reg.fit(X, y, verbose=10)
c = reg.get_coef()
c

i = 0 | loss = 810.9197945296903
i = 10 | loss = 606.6150502834279
i = 20 | loss = 487.2410882189987
i = 30 | loss = 407.11219048695597
i = 40 | loss = 347.0692499463499
i = 50 | loss = 298.7940110048301


array([  0.35326258,  10.50815526,   2.16887989, -10.87486366])

In [ ]:
def calc_mse(y, y_pred):
    print(y)
    print(y_pred)
    err = np.mean((y - y_pred)**2)
    return err

X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)
X.columns = [f'col_{col}' for col in X.columns]

X = X.to_numpy()
y = y.to_numpy()

X
# W = np.ones(X.shape[1])
# W
# y_pred = np.dot(X, W)
# y_pred
# # y

# print(X.shape)

def alpha_iter_search(X, alpha=1e-2, n_iter=100):
  """Алгоритм градиентного спуска, завершающий работу по превышению количества итераций
       Альфа неизменна"""
  n = X.shape[1]
  W = np.ones(X.shape[1])
  print(f'Number of objects = {n} \
       \nLearning rate = {alpha} \
       \nInitial weights = {W} \n')

  for i in range(n_iter):
        y_pred = np.dot(X, W)
        err = calc_mse(y, y_pred)

        for k in range(len(W)):
            W[k] -= alpha * (1/n * 2 * np.sum(X[k] * (y_pred - y)))
        if i % 50 == 0:
            # alpha /= 1.1
            print(f'Iteration #{i} W_new = {W}, MSE = {round(err, 2)}')

alpha_iter_search(X, alpha=0.05, n_iter=300)

print('Подобранный вариант скорости обучения = 0.05')

Number of objects = 3        
Learning rate = 0.05        
Initial weights = [1. 1. 1.] 

[-33.38737028  21.12932958]
[1.05473952 1.00613839]


ValueError: ignored

In [ ]:
def calc_mse(y, y_pred):
    print(y)
    print(y_pred)
    err = np.mean((y - y_pred)**2)
    return err

X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)
X.columns = [f'col_{col}' for col in X.columns]

X = X.to_numpy()
y = y.to_numpy()

def alpha_iter_search(X, alpha=1e-2, n_iter=100):
  """Алгоритм градиентного спуска, завершающий работу по превышению количества итераций
       Альфа неизменна"""
  n = X.shape[1]
  W = np.ones(X.shape[0])
  print(f'Number of objects = {n} \
       \nLearning rate = {alpha} \
       \nInitial weights = {W} \n')

  for i in range(n_iter):
        y_pred = np.dot(W, X)
        err = calc_mse(y, y_pred)

#### GB variant

In [ ]:
X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)
X.columns = [f'col_{col}' for col in X.columns]

X = X.to_numpy()
y = y.to_numpy()

In [ ]:
y

array([-33.38737028,  21.12932958])

In [ ]:
# X = np.array([[-0.23413696, -0.23415337,  1.52302986],
#        [ 0.64768854, -0.1382643 ,  0.49671415]])

X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 5, 3, 0, 5, 10, 1, 2]])
X

y = [45, 55, 50, 55, 60, 35, 75, 80, 50, 60]
# y=[-33.38737028,  21.12932958]

def calc_mse(y, y_pred):
    err = np.mean((y - y_pred)**2)
    return err


def alpha_iter_search(X, alpha=1e-2, n_iter=100):
  """Алгоритм градиентного спуска, завершающий работу по превышению количества итераций
       Альфа неизменна"""
  n = X.shape[1]
  W = np.array([1, .5])
  print(f'Number of objects = {n} \
       \nLearning rate = {alpha} \
       \nInitial weights = {W} \n')

  for i in range(n_iter):
        y_pred = np.dot(W, X)
        # print(y_pred.shape)
        err = calc_mse(y, y_pred)
        for k in range(len(W)):
            W[k] -= alpha * (1/n * 2 * np.sum(X[k] * (y_pred - y)))
        if i % 50 == 0:
            # alpha /= 1.1
            print(f'Iteration #{i} W_new = {W}, MSE = {round(err, 2)}')

alpha_iter_search(X, alpha=0.05, n_iter=300)

print('Подобранный вариант скорости обучения = 0.05')

Number of objects = 10        
Learning rate = 0.05        
Initial weights = [1.  0.5] 

Iteration #0 W_new = [ 6.4  19.35], MSE = 3047.75
Iteration #50 W_new = [41.16920131  4.51849616], MSE = 51.81
Iteration #100 W_new = [44.68506002  3.88094292], MSE = 44.04
Iteration #150 W_new = [45.02590869  3.81913527], MSE = 43.97
Iteration #200 W_new = [45.05895262  3.81314326], MSE = 43.97
Iteration #250 W_new = [45.0621561   3.81256236], MSE = 43.97
Подобранный вариант скорости обучения = 0.05


#### Another решение.

In [ ]:
X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)
X.columns = [f'col_{col}' for col in X.columns]

class MyLineReg:

    n_iter_: int = 2
    learning_rate_: float = 0.1
    weights_: pd.Series = None

    def __init__(self,  n_iter=n_iter_, learning_rate=learning_rate_) -> None:
        self.n_iter_ = n_iter
        self.learning_rate_ = learning_rate
        self.weights_ = None

    def __str__(self) -> str:
        return f'MyLineReg class: n_iter={self.n_iter_}, learning_rate={self.learning_rate_}'

    @staticmethod
    def MSE(prediction: pd.Series, y: pd.Series) -> float:
        return 1 / y.shape[0] * sum((prediction - y) ** 2)

    @staticmethod
    def grad_mse(prediction: pd.Series, y: pd.Series, X: pd.DataFrame) -> pd.Series:
        return pd.Series(2 / y.shape[0] * (prediction - y) @ X)

    def fit(self, X: pd.DataFrame, y: pd.Series, verbose=False) -> None:
        X.insert(0, '', np.ones(X.shape[0]))
        X, y = X.values, y.values
        weights = pd.Series(np.ones(X.shape[1]))
        # prediction = X @ weights

        # if verbose:
        #     print(f'start | loss: {self.MSE(prediction, y)}')

        for iter in range(self.n_iter_):
            prediction = X @ weights
            mse_iter = self.MSE(prediction, y)
            grad = self.grad_mse(prediction, y, X)
            # print(grad)
            weights -= self.learning_rate_ * grad
            self.weights_ = weights

            if verbose and iter % verbose == 0:
                print(f'{iter} | loss: {mse_iter}')

        return None

    def get_coef(self):
        return self.weights_[1:]

reg = MyLineReg()
reg.fit(X, y, verbose=0)
c = reg.get_coef()
c

1    5.092662
2    1.884018
3   -6.393735
dtype: float64

In [ ]:
X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)
X.columns = [f'col_{col}' for col in X.columns]

class MyLineReg():

    n_iter_: int = 2
    learning_rate_: float = 0.1
    weights_: pd.Series = None


    def __init__(self,  n_iter=n_iter_, learning_rate=learning_rate_) -> None:
        self.n_iter_ = n_iter
        self.learning_rate_ = learning_rate
        self.weights_ = None

    def __repr__(self):
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    @staticmethod
    def MSE(prediction: pd.Series, y: pd.Series) -> float:
        return 1 / y.shape[0] * sum((prediction - y) ** 2)

    @staticmethod
    def grad_mse(prediction: pd.Series, y: pd.Series, X: pd.DataFrame) -> pd.Series:
        return pd.Series(2 / y.shape[0] * (prediction - y) @ X)

    def fit(self, X, y, verbose=False):
        X.insert(loc=0, column='x_0', value=1)
        X, y = X.values, y.values

        # w = np.ones(X.shape[1])
        w = pd.Series(np.ones(X.shape[1]))

        for i in range(self.n_iter_):
            # y_tilda = np.dot(X, w)
            prediction = X @ w
            mse_iter = self.MSE(prediction, y)
            # nabla_mse = (2 / y.shape[0]) * ((prediction - y)).dot(X)
            w -= self.learning_rate_ * mse_iter

            if verbose != False and i % verbose == 0:
              err = np.mean((y - prediction)**2)
              print(f'i = {i} | loss = {err}')
            self.weights = w

    def get_coef(self):
      return self.weights

reg = MyLineReg()
reg.fit(X, y, verbose=1)

i = 0 | loss = 810.9197945296903
i = 1 | loss = 25130.71449162592


In [ ]:
X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)
X.columns = [f'col_{col}' for col in X.columns]

class MyLineReg():
    def __init__(self, n_iter=2, learning_rate=0.1, weights=None):
        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights

    def __repr__(self):
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    def fit(self, X, y, verbose=False):
        X.to_numpy()
        y.to_numpy()
        X = np.c_[np.ones(X.shape[0]), X]
        w = np.ones(X.shape[1])

        y_tilda = np.dot(X, w)


        if verbose:
            print(f'start | loss: {np.mean((y_tilda - y)**2)}')

        for i in range(self.n_iter):
            y_tilda = np.dot(X, w)
            # print(y_tilda)
            nabla_mse = (2 / y.shape[0]) * ((y_tilda - y)).dot(X)
            print(nabla_mse)
            w -= self.learning_rate * nabla_mse

            if verbose and i % verbose == 0:
              err = np.mean((y_tilda - y)**2)
              # err = 1 / y.shape[0] * sum((y_tilda - y) ** 2)
              print(f'i = {i} | loss = {err}')

            self.weights = w

    def get_coef(self):
      return self.weights[1:]


reg = MyLineReg()
reg.fit(X, y, verbose=1)
c = reg.get_coef()
c

start | loss: 810.9197945296903
[ 16.31891862 -20.68417949  -5.65483495  44.4806317 ]
i = 0 | loss = 810.9197945296903
[  4.71598742 -20.24244087  -3.18534441  29.45671377]
i = 1 | loss = 584.491291098404


array([ 5.09266204,  1.88401794, -6.39373455])

##### Верное решение numpy.

In [ ]:
#### Верное решение numpy.
X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)
X.columns = [f'col_{col}' for col in X.columns]

class MyLineReg():
    def __init__(self, n_iter=50, learning_rate=0.1, weights=None) -> None:
        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights

    def __repr__(self) -> str:
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    def fit(self, X, y, verbose=False) -> None:
        X.to_numpy()
        y.to_numpy()
        X = np.c_[np.ones(X.shape[0]), X]
        w = np.ones(X.shape[1])

        y_tilda = np.dot(X, w)

        for i in range(self.n_iter):
            y_tilda = np.dot(X, w)
            nabla_mse = (2 / y.shape[0]) * ((y_tilda - y)).dot(X)
            w -= self.learning_rate * nabla_mse

            if verbose and i % verbose == 0:
              err = np.mean((y_tilda - y)**2)
              print(f'start | loss = {err}') if i == 0 else print(f'i = {i} | loss = {err}')

            self.weights = w

    def get_coef(self):
      return self.weights[1:]

reg = MyLineReg()
reg.fit(X, y, verbose=10)

start | loss = 810.9197945296903
i = 10 | loss = 139.81959864186436
i = 20 | loss = 32.585779251323856
i = 30 | loss = 7.594408275896183
i = 40 | loss = 1.7699450010116582


# 2_1_7


Предсказание
Ну, и третьим (обязательным) шагом мы научим нашу модель выдавать предсказания...

Добавьте в класс MyLineReg метод predict. Данный метод должен делать следующее:

На вход принимать матрицу фичей в виде датафрейма пандаса.
Дополнять матрицу фичей единичным вектором (первый столбец).
Возвращать вектор предсказаний.
Напомню, что предсказание выполняется следующим образом:
�
^
=
�
�
y
^
​
 =XW

где:
-
X - матрица фичей
-
W - вектор весов

Проверка

Входные данные: три датасета с различными параметрами (сгенерированными посредством метода make_regression из scikit-learn)
Выходные данные: возвращенные предсказания (их сумма)

## numpy

In [ ]:
X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)
X.columns = [f'col_{col}' for col in X.columns]

class MyLineReg():
    def __init__(self, n_iter=50, learning_rate=0.1, weights=None) -> None:
        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights

    def __repr__(self) -> str:
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    def fit(self, X, y, verbose=False) -> None:
        X.to_numpy()
        y.to_numpy()
        X = np.c_[np.ones(X.shape[0]), X]
        w = np.ones(X.shape[1])

        y_tilda = np.dot(X, w)

        for i in range(self.n_iter):
            y_tilda = np.dot(X, w)
            nabla_mse = (2 / y.shape[0]) * ((y_tilda - y)).dot(X)
            w -= self.learning_rate * nabla_mse

            if verbose and i % verbose == 0:
              err = np.mean((y_tilda - y)**2)
              print(f'start | loss = {err}') if i == 0 else print(f'i = {i} | loss = {err}')

            self.weights = w

    def get_coef(self):
      return self.weights[1:]

    def predict(self, X):
         X.to_numpy()
         X = np.c_[np.ones(X.shape[0]), X]

        #  y_pred = np.dot(X, self.weights)

        #  return np.sum(y_pred)
         return np.dot(X, self.weights)

reg = MyLineReg()
reg.fit(X, y, verbose=10)
reg.predict(X)

start | loss = 810.9197945296903
i = 10 | loss = 139.81959864186436
i = 20 | loss = 32.585779251323856
i = 30 | loss = 7.594408275896183
i = 40 | loss = 1.7699450010116582


array([-32.91982746,  20.3506083 ])

## pandas

In [ ]:
X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# X = pd.DataFrame(X_mk)
# y = pd.Series(y_mk)
# X.columns = [f'col_{col}' for col in X.columns]

class MyLineReg():
    def __init__(self, n_iter=50, learning_rate=0.01, weights=None) -> None:
        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights

    def __repr__(self):
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    def fit(self, X, y, verbose=False):
        X.insert(loc=0, column='x_0', value=1)
        w = np.ones(X.shape[1])

        for i in range(self.n_iter):
            y_tilda = np.dot(X, w)
            nabla_mse = (2 / y.shape[0]) * ((y_tilda - y)).dot(X)
            w -= self.learning_rate * nabla_mse

            if verbose != False and i % verbose == 0:
              err = np.mean((y - y_tilda)**2)
              print(f'i = {i} | loss = {err}')
            self.weights = w.to_numpy()

    def get_coef(self):
      return self.weights[1:]

    def predict(self, X):
         X.insert(loc=0, column='x_x', value=1)

         return np.dot(X, self.weights)


reg = MyLineReg()
reg.fit(X_train, y_train, verbose=10)
reg.predict(X_test)

i = 0 | loss = 1256.1431476987827
i = 10 | loss = 303.3195182707737
i = 20 | loss = 73.24223384298229
i = 30 | loss = 17.685722464853963
i = 40 | loss = 4.2705521485648905


array([-14.43018977])

# 2_1_9


Метрики (реализация)
Теперь реализуем метрики на практике:

Добавьте в класс MyLineReg параметр metric, который будет принимать одно из следующих значений:
- mae
- mse
- rmse
- mape
- r2

По умолчанию: None

При обучении добавьте в вывод расчет метрики:

start | loss: 42027.65 | <metric_name>: 234.65

100 | loss: 1222.87 | <metric_name>: 114.35

200 | loss: 232.17 | <metric_name>: 58.2

300 | loss: 202.4 | <metric_name>: 46.01

Если метрика не задана, то ничего дополнительно выводить не нужно.
Добавьте метод get_best_score, который возвращает последнее значение метрики (т.е. уже полностью обученной модели).

Примечания:

Хотя мы теперь отслеживаем и другие метрики, градиентный спуск все равно выполняется по среднеквадратичной ошибке.
Зачем мы добавили метрику MSE если у нас и так функция потерь это MSE? Во-первых, функцией потерь может быть не только MSE. Во-вторых, далее мы добавим к функции потерь регуляризацию, которая будет влиять на ее результат. А на метрику регуляризация влиять не должна.

Проверка

Входные данные: названия всех метрик
Выходные данные: значение метрики полученное после обучения модели

In [ ]:
X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)
X.columns = [f'col_{col}' for col in X.columns]

class MyLineReg():
    def __init__(self, n_iter=50, learning_rate=0.1, weights=None, metric=None) -> None:
        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights
        self.metric = metric

    def __repr__(self) -> str:
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    @staticmethod
    def get_best_score(metric, y, y_tilda):
        if metric == 'mae':
            metr = np.sum(abs(y - y_tilda))
        elif metric == 'mse':
            metr = np.mean((y_tilda - y)**2)
        elif metric == 'rmse':
            metr = np.sqrt(np.mean((y_tilda - y)**2))
        elif metric == 'mape':
            metr = (100 / y.shape[0]) * np.sum(abs((y - y_tilda) / y_tilda))
        elif metric == 'r2':
            metr = 1 - ((np.sum((y - y_tilda)**2)) / (np.sum((y - np.mean(y))**2)))
        return metr

    def fit(self, X, y, verbose=False) -> None:
        X.to_numpy()
        y.to_numpy()
        X = np.c_[np.ones(X.shape[0]), X]
        w = np.ones(X.shape[1])

        y_tilda = np.dot(X, w)

        for i in range(self.n_iter):
            y_tilda = np.dot(X, w)
            nabla_mse = (2 / y.shape[0]) * ((y_tilda - y)).dot(X)
            w -= self.learning_rate * nabla_mse

            metr = self.get_best_score(self.metric, y, y_tilda) if self.metric else None

            if verbose and i % verbose == 0:
              err = np.mean((y_tilda - y)**2)
              if metr != None:
                  print(f'start | loss = {err}') if i == 0 else print(f'i = {i} | loss = {err} | {metr}')
              else:
                  print(f'start | loss = {err}') if i == 0 else print(f'i = {i} | loss = {err}')

            self.weights = w

    def get_coef(self):
        return self.weights[1:]

    def predict(self, X):
        X.to_numpy()
        X = np.c_[np.ones(X.shape[0]), X]

        return np.dot(X, self.weights)

reg = MyLineReg()
reg.fit(X, y, verbose=10)
# reg.predict(X)

start | loss = 810.9197945296903
i = 10 | loss = 139.81959864186436
i = 20 | loss = 32.585779251323856
i = 30 | loss = 7.594408275896183
i = 40 | loss = 1.7699450010116582


In [ ]:
X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)
X.columns = [f'col_{col}' for col in X.columns]

class MyLineReg():
    def __init__(self, n_iter=50, learning_rate=0.1, weights=None, metric=None) -> None:
        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights
        self.metric = metric

    def __repr__(self) -> str:
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"


    def get_best_score(self):
        if self.metric == 'mae':
            metr = np.sum(abs(self.y - self.y_tilda))
        elif self.metric == 'mse':
            metr = np.mean((self.y_tilda - self.y)**2)
        elif self.metric == 'rmse':
            metr = np.sqrt(np.mean((self.y_tilda - self.y)**2))
        elif self.metric == 'mape':
            metr = (100 / self.y.shape[0]) * np.sum(abs((self.y - self.y_tilda) / self.y_tilda))
        elif self.metric == 'r2':
            metr = 1 - ((np.sum((self.y - self.y_tilda)**2)) / (np.sum((self.y - np.mean(self.y))**2)))
        return metr

    def fit(self, X, y, verbose=False) -> None:
        X.to_numpy()
        y.to_numpy()
        X = np.c_[np.ones(X.shape[0]), X]
        w = np.ones(X.shape[1])

        y_tilda = np.dot(X, w)
        self.y = y
        self.y_tilda = y_tilda

        for i in range(self.n_iter):
            y_tilda = np.dot(X, w)
            nabla_mse = (2 / y.shape[0]) * ((y_tilda - y)).dot(X)
            w -= self.learning_rate * nabla_mse

            metr = self.get_best_score() if self.metric else None

            if verbose and i % verbose == 0:
              err = np.mean((y_tilda - y)**2)
              if metr != None:
                  print(f'start | loss = {err}') if i == 0 else print(f'i = {i} | loss = {err} | {metr}')
              else:
                  print(f'start | loss = {err}') if i == 0 else print(f'i = {i} | loss = {err}')

            self.weights = w

    def get_coef(self):
        return self.weights[1:]

    def predict(self, X):
        X.to_numpy()
        X = np.c_[np.ones(X.shape[0]), X]

        return np.dot(X, self.weights)

reg = MyLineReg()
reg.get_best_score()

1

Перепишем заново

## numpy

In [ ]:
# рабочая версия, но она на нампае, а нужно в пандас перевести.

X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)
X.columns = [f'col_{col}' for col in X.columns]

class MyLineReg():
    def __init__(self,
                 n_iter=3,
                 learning_rate= 0.1,
                 weights = None,
                 metric=None) -> None:

        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights
        self.metric = metric

    def __repr__(self) -> str:
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    def get_best_score(self):
        return self.score

    @staticmethod
    def get_metric_score(metric, y, y_tilda):
        if metric == 'mae':
            score = (y - y_tilda).abs().mean()
        elif metric == 'mse':
            score = np.mean((y_tilda - y)**2)
        elif metric == 'rmse':
            score = np.sqrt(np.mean((y_tilda - y)**2))
        elif metric == 'mape':
            score = (100 / y.shape[0]) * np.sum(abs((y - y_tilda) / y_tilda))
        elif metric == 'r2':
            score = 1 - ((np.sum((y - y_tilda)**2)) / (np.sum((y - np.mean(y))**2)))
        return score

    def fit(self, X, y, verbose=False) -> None:
        X.to_numpy()
        y.to_numpy()
        X = np.c_[np.ones(X.shape[0]), X]
        w = np.ones(X.shape[1])


        for i in range(self.n_iter):
            y_tilda = np.round(np.dot(X, w), 6)
            err = np.mean((y_tilda - y)**2)
            nabla_mse = (2 / y.shape[0]) * ((y_tilda - y)).dot(X)

            w -= self.learning_rate * nabla_mse

            if self.metric:
               self.score = getattr(self, 'get_metric_score')(self.metric, y, np.dot(X, w))

            if verbose and i % verbose == 0:
              if self.metric:
                  print(f'start | loss = {err} | {self.score}') if i == 0 else print(f'i = {i} | loss = {err} | {self.score}')
              else:
                  print(f'start | loss = {err}') if i == 0 else print(f'i = {i} | loss = {err}')

            self.weights = w

reg = MyLineReg(metric='mae')
# reg.get_best_score()
reg.fit(X, y, verbose=10)

start | loss = 810.9198188309781 | 24.06098823146364


## pandas

In [ ]:
X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)

class MyLineReg():
    def __init__(self,
                 n_iter=3,
                 learning_rate= 0.1,
                 weights = None,
                 metric=None) -> None:

        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights
        self.metric = metric

    def __repr__(self):
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    def get_best_score(self):
        return self.score


    def get_coef(self):
      return self.weights[1:]

    def predict(self, X):
         X.insert(loc=0, column='x_x', value=1)

         return np.dot(X, self.weights)

    @staticmethod
    def get_metric_score(metric, y, y_tilda):
        if metric == 'mae':
            score = (y - y_tilda).abs().mean()
        elif metric == 'mse':
            score = np.mean((y_tilda - y)**2)
        elif metric == 'rmse':
            score = np.sqrt(np.mean((y_tilda - y)**2))
        elif metric == 'mape':
            score = (100 / y.shape[0]) * np.sum(abs((y - y_tilda) / y))
            # score = 100 * ((y - y_tilda) / y).abs().mean()
        elif metric == 'r2':
            score = 1 - ((np.sum((y - y_tilda)**2)) / (np.sum((y - np.mean(y))**2)))
        return score

    def fit(self, X, y, verbose=False):
        X.insert(loc=0, column='x_0', value=1)
        w = np.ones(X.shape[1])

        for i in range(self.n_iter):
            y_tilda = np.dot(X, w)
            err = np.mean((y_tilda - y)**2)
            nabla_mse = (2 / y.shape[0]) * ((y_tilda - y)).dot(X)
            w -= self.learning_rate * nabla_mse

            if self.metric:
               self.score = getattr(self, 'get_metric_score')(self.metric, y, np.dot(X, w))

            if verbose and i % verbose == 0:
              if self.metric:
                  print(f'start | loss = {err} | {self.score}') if i == 0 else print(f'i = {i} | loss = {err} | {self.score}')
              else:
                  print(f'start | loss = {err}') if i == 0 else print(f'i = {i} | loss = {err}')

            self.weights = w.to_numpy()


reg = MyLineReg(metric='mape')
reg.fit(X, y, verbose=10)

start | loss = 810.9197945296903 | 90.92184361849664


In [ ]:
# верное решение

class MyLineReg():
    def __init__(self,
                 n_iter=3,
                 learning_rate= 0.1,
                 weights = None,
                 metric=None) -> None:

        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights
        self.metric = metric

    def __repr__(self):
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    def get_best_score(self):
        return self.score


    def get_coef(self):
      return self.weights[1:]

    def predict(self, X):
         X.insert(loc=0, column='x_x', value=1)

         return np.dot(X, self.weights)

    @staticmethod
    def get_metric_score(metric, y, y_tilda):
        if metric == 'mae':
            score = (y - y_tilda).abs().mean()
        elif metric == 'mse':
            score = np.mean((y_tilda - y)**2)
        elif metric == 'rmse':
            score = np.sqrt(np.mean((y_tilda - y)**2))
        elif metric == 'mape':
            score = (100 / y.shape[0]) * np.sum(abs((y - y_tilda) / y))
        elif metric == 'r2':
            score = 1 - ((np.sum((y - y_tilda)**2)) / (np.sum((y - np.mean(y))**2)))
        return score

    def fit(self, X, y, verbose=False):
        X.insert(loc=0, column='x_0', value=1)
        w = np.ones(X.shape[1])

        for i in range(self.n_iter):
            y_tilda = np.dot(X, w)
            err = np.mean((y_tilda - y)**2)
            nabla_mse = (2 / y.shape[0]) * ((y_tilda - y)).dot(X)
            w -= self.learning_rate * nabla_mse

            if self.metric:
               self.score = getattr(self, 'get_metric_score')(self.metric, y, np.dot(X, w))

            if verbose and i % verbose == 0:
              if self.metric:
                  print(f'start | loss = {err} | {self.score}') if i == 0 else print(f'i = {i} | loss = {err} | {self.score}')
              else:
                  print(f'start | loss = {err}') if i == 0 else print(f'i = {i} | loss = {err}')

            self.weights = w.to_numpy()

## Another решение.

In [ ]:
from sklearn.model_selection import train_test_split

In [84]:
X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)
X.columns = [f'col_{col}' for col in X.columns]


class MyLineReg:
    def __init__(self,
                 n_iter: int = 3,
                 learning_rate: float = 0.1,
                 metric: str = None,
                 reg: str = 'None',
                 l1_coef: float = 0.,
                 l2_coef: float = 0.,
                 sgd_sample: float = None,
                 random_state: int = 42) -> None:
        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self._weights = None
        self.metric = metric
        self.reg = reg  # 'l1', 'l2', 'elasticnet'
        self.l1_coef = l1_coef
        self.l2_coef = l2_coef
        self.sgd_sample = sgd_sample
        # random.seed(random_state)

    def __str__(self) -> str:
        params = [f'{key}={value}' for key, value in self.__dict__.items()]
        return 'MyLineReg class: ' + ', '.join(params)

    @staticmethod
    def _mae(y_true: pd.Series, y_pred: pd.Series):
        return (y_true - y_pred).abs().mean()

    @staticmethod
    def _mse(y_true: pd.Series, y_pred: pd.Series):
        return (y_true - y_pred).pow(2).mean()

    @staticmethod
    def _rmse(y_true: pd.Series, y_pred: pd.Series):
        return np.sqrt((y_true - y_pred).pow(2).mean())

    @staticmethod
    def _mape(y_true: pd.Series, y_pred: pd.Series):
        return 100 * ((y_true - y_pred) / y_true).abs().mean()

    @staticmethod
    def _r2(y_true: pd.Series, y_pred: pd.Series):
        return 1 - (y_true - y_pred).pow(2).sum() / ((y_true - y_true.mean()).pow(2).sum())

    def get_best_score(self):
        return self.score


    def loss(self, y_true: pd.Series, y_pred: pd.Series) -> float:
        if self.reg == 'None':
            return (y_pred - y_true).pow(2).mean()
        elif self.reg == 'l1':
            return (y_pred - y_true).pow(2).mean() +\
                self.l1_coef * self._weights.abs().sum()
        elif self.reg == 'l2':
            return (y_pred - y_true).pow(2).mean() +\
                self.l2_coef * self._weights.pow(2).sum()
        else:
            return (y_pred - y_true).pow(2).mean() +\
                self.l1_coef * self._weights.abs().sum() +\
                self.l2_coef * (self._weights.pow(2).sum())

    def grad(self, y_true: pd.Series, y_pred: pd.Series, x: pd.DataFrame, mini_batch_idx: pd.DataFrame.index):
        y_true = y_true.iloc[mini_batch_idx]
        y_pred = y_pred.iloc[mini_batch_idx]
        x = x.iloc[mini_batch_idx, :]

        if not self.reg:
            return (2 / y_true.shape[0]) * (y_pred - y_true) @ x
        elif self.reg == 'l1':
            return (2 / y_true.shape[0]) * (y_pred - y_true) @ x +\
                self.l1_coef * np.sign(self._weights)
        elif self.reg == 'l2':
            return (2 / y_true.shape[0]) * (y_pred - y_true) @ x +\
                self.l2_coef * 2 * self._weights
        else:
            return (2 / y_true.shape[0]) * (y_pred - y_true) @ x +\
                self.l1_coef * np.sign(self._weights) +\
                self.l2_coef * 2 * self._weights

    # def _get_minibatch_idx(self, x_length, sample) -> pd.DataFrame.index:
    #     sample = int(sample * x_length) if isinstance(sample, float) else sample
    #     return random.sample(range(x_length), sample)

    def fit(self, x: pd.DataFrame, y: pd.Series, verbose: int) -> None:
        x = pd.concat([pd.Series([1] * x.shape[0], index=x.index), x], axis=1)
        self._weights = pd.Series([1.] * x.shape[1], index=x.columns)
        for i in range(self.n_iter):
            mini_batch_idx = self._get_minibatch_idx(x.shape[0], self.sgd_sample) if self.sgd_sample else x.index
            y_hat = self._weights @ x.T
            loss = self.loss(y, y_hat)
            grad = self.grad(y, y_hat, x, mini_batch_idx)
            if isinstance(self.learning_rate, (int, float)):
                self._weights -= self.learning_rate * grad
            else:
                self._weights -= self.learning_rate(i + 1) * grad
            if self.metric:
                self.score = getattr(self, '_' + self.metric)(y, x @ self._weights)
            if verbose and i % verbose == 0:
                if self.metric:
                    print(f'{i} | loss: {loss} | {self.metric}: {self.score}')
                else:
                    print(f'{i} | loss: {loss}')

    def get_coef(self):
        return self._weights[1:]

    def predict(self, x: pd.DataFrame):
        x = pd.concat([pd.Series([1] * x.shape[0], index=x.index), x], axis=1).values
        return x @ self._weights


# X, y = make_regression(n_samples=400, n_features=14, n_informative=5, noise=5, random_state=42)
# X = pd.DataFrame(X)
# y = pd.Series(y)
# X.columns = [f'col_{col}' for col in X.columns]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

reg = MyLineReg(metric='mae')
# reg.fit(X_train, y_train, 20)


# print(reg.get_coef().sum())

# reg.get_best_score()

reg.fit(X, y, 10)

0 | loss: 4690.118351259567 | mae: 46.51753895770776


In [ ]:
y = np.array([-33.38737, 21.12933])
# y_tilda = np.array([2.05474,  2.006138])
y_tilda = np.array([2.054740, 2.006138])

np.abs(y_tilda - y).mean()

27.282651

# 2_1_11

In [7]:
X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)

class MyLineReg():
    def __init__(self,
                 n_iter=3,
                 learning_rate= 0.1,
                 weights = None,
                 metric=None,
                 reg=None,
                 l1_coef: float = 0.,
                 l2_coef: float = 0.,) -> None:

        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights
        self.metric = metric
        self.reg = reg
        self.l1_coef = l1_coef
        self.l2_coef = l2_coef

    def __repr__(self):
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    def get_best_score(self):
        return self.score

    def get_coef(self):
      return self.weights[1:]

    def predict(self, X):
         X.insert(loc=0, column='x_x', value=1)

         return np.dot(X, self.weights)

    @staticmethod
    def get_metric_score(metric, y, y_pred):
        if metric == 'mae':
            score = (y - y_pred).abs().mean()
        elif metric == 'mse':
            score = np.mean((y_pred - y)**2)
        elif metric == 'rmse':
            score = np.sqrt(np.mean((y_pred - y)**2))
        elif metric == 'mape':
            score = (100 / y.shape[0]) * np.sum(abs((y - y_pred) / y))
        elif metric == 'r2':
            score = 1 - ((np.sum((y - y_pred)**2)) / (np.sum((y - np.mean(y))**2)))
        return score

    def grad(self, y_true: pd.Series, y_pred: pd.Series, X: pd.DataFrame):

        if not self.reg:
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X)
        elif self.reg == 'l1':
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X) + self.l1_coef * np.sign(self.weights)
        elif self.reg == 'l2':
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X) + self.l2_coef * 2 * (self.weights)
        elif self.reg == 'elasticnet':
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X) + self.l1_coef * np.sign(self.weights) + self.l2_coef * 2 * (self.weights)

        return grad

    def fit(self, X, y, verbose=False):
        X.insert(loc=0, column='x_0', value=1)
        # w = np.ones(X.shape[1])

        self.weights = np.ones(X.shape[1])

        for i in range(self.n_iter):
            y_pred = np.dot(X, self.weights)
            err = np.mean((y_pred - y)**2)
            # nabla_mse = (2 / y.shape[0]) * ((y_pred - y)).dot(X)
            nabla = self.grad(y, y_pred, X)

            self.weights -= self.learning_rate * nabla

            if self.metric:
               self.score = getattr(self, 'get_metric_score')(self.metric, y, np.dot(X, self.weights))

            if verbose and i % verbose == 0:
              if self.metric:
                  print(f'start | loss = {err} | {self.score}') if i == 0 else print(f'i = {i} | loss = {err} | {self.score}')
              else:
                  print(f'start | loss = {err}') if i == 0 else print(f'i = {i} | loss = {err}')

            # self.weights = w.to_numpy()


reg = MyLineReg(metric='mape')
reg.fit(X, y, verbose=10)

start | loss = 810.9197945296903 | 90.92184361849664


In [ ]:
# correct version

class MyLineReg():
    def __init__(self,
                 n_iter=3,
                 learning_rate= 0.1,
                 weights = None,
                 metric=None,
                 reg=None,
                 l1_coef: float = 0.,
                 l2_coef: float = 0.,) -> None:

        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights
        self.metric = metric
        self.reg = reg
        self.l1_coef = l1_coef
        self.l2_coef = l2_coef

    def __repr__(self):
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    def get_best_score(self):
        return self.score

    def get_coef(self):
        return self.weights[1:]

    def predict(self, X):
         X.insert(loc=0, column='x_x', value=1)

         return np.dot(X, self.weights)

    @staticmethod
    def get_metric_score(metric, y, y_pred):
        if metric == 'mae':
            score = (y - y_pred).abs().mean()
        elif metric == 'mse':
            score = np.mean((y_pred - y)**2)
        elif metric == 'rmse':
            score = np.sqrt(np.mean((y_pred - y)**2))
        elif metric == 'mape':
            score = (100 / y.shape[0]) * np.sum(abs((y - y_pred) / y))
        elif metric == 'r2':
            score = 1 - ((np.sum((y - y_pred)**2)) / (np.sum((y - np.mean(y))**2)))
        return score

    def grad(self, y_true: pd.Series, y_pred: pd.Series, X: pd.DataFrame):

        if not self.reg:
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X)
        elif self.reg == 'l1':
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X) + self.l1_coef * np.sign(self.weights)
        elif self.reg == 'l2':
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X) + self.l2_coef * 2 * (self.weights)
        elif self.reg == 'elasticnet':
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X) + self.l1_coef * np.sign(self.weights) + self.l2_coef * 2 * (self.weights)

        return grad

    def fit(self, X, y, verbose=False):
        X.insert(loc=0, column='x_0', value=1)

        self.weights = np.ones(X.shape[1])

        for i in range(self.n_iter):
            y_pred = np.dot(X, self.weights)
            err = np.mean((y_pred - y)**2)
            nabla = self.grad(y, y_pred, X)

            self.weights -= self.learning_rate * nabla

            if self.metric:
               self.score = getattr(self, 'get_metric_score')(self.metric, y, np.dot(X, self.weights))

            if verbose and i % verbose == 0:
               if self.metric:
                   print(f'start | loss = {err} | {self.score}') if i == 0 else print(f'i = {i} | loss = {err} | {self.score}')
               else:
                   print(f'start | loss = {err}') if i == 0 else print(f'i = {i} | loss = {err}')

# 2_1_12

Возьмите код из предыдущего шага и модифицируйте в нем параметр learning_rate следующим:

Если на вход пришло число, то работаем как и раньше.
Если на вход пришла lambda-функция, то вычисляем learning_rate на каждом шаге на основе переданной лямбда-функции.
Можете дополнительно для контроля вывести значение learning_rate в лог тренировки.

Примечания:

Т.к. у нас теперь результат зависит от нумерации шагов, то формализуем их нумерацию: они должна считаться от 1 до n_iter (включительно).
Проверка


Входные данные: три различных значения для скорости обучения, два из которых — динамические

Выходные данные: коэффициенты обученной линейной регрессии (их сумма)

In [8]:
def f():
  pass

isinstance(f)

TypeError: ignored

In [ ]:
class MyLineReg():
    def __init__(self,
                 n_iter=3,
                 learning_rate= 0.1,
                 weights = None,
                 metric=None,
                 reg=None,
                 l1_coef: float = 0.,
                 l2_coef: float = 0.,) -> None:

        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights
        self.metric = metric
        self.reg = reg
        self.l1_coef = l1_coef
        self.l2_coef = l2_coef

    def __repr__(self):
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    def get_best_score(self):
        return self.score

    def get_coef(self):
        return self.weights[1:]

    def predict(self, X):
         X.insert(loc=0, column='x_x', value=1)

         return np.dot(X, self.weights)

    @staticmethod
    def get_metric_score(metric, y, y_pred):
        if metric == 'mae':
            score = (y - y_pred).abs().mean()
        elif metric == 'mse':
            score = np.mean((y_pred - y)**2)
        elif metric == 'rmse':
            score = np.sqrt(np.mean((y_pred - y)**2))
        elif metric == 'mape':
            score = (100 / y.shape[0]) * np.sum(abs((y - y_pred) / y))
        elif metric == 'r2':
            score = 1 - ((np.sum((y - y_pred)**2)) / (np.sum((y - np.mean(y))**2)))
        return score

    def grad(self, y_true: pd.Series, y_pred: pd.Series, X: pd.DataFrame):

        if not self.reg:
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X)
        elif self.reg == 'l1':
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X) + self.l1_coef * np.sign(self.weights)
        elif self.reg == 'l2':
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X) + self.l2_coef * 2 * (self.weights)
        elif self.reg == 'elasticnet':
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X) + self.l1_coef * np.sign(self.weights) + self.l2_coef * 2 * (self.weights)

        return grad

    def fit(self, X, y, verbose=False):
        X.insert(loc=0, column='x_0', value=1)

        self.weights = np.ones(X.shape[1])

        for i in range(self.n_iter):
            y_pred = np.dot(X, self.weights)
            err = np.mean((y_pred - y)**2)
            nabla = self.grad(y, y_pred, X)

            if isinstance(self.learning_rate, (int, float)):
                self.weights -= self.learning_rate * nabla
            else:
                self.weights -= self.learning_rate(i + 1) * nabla

            # self.weights -= self.learning_rate * nabla if isinstance(self.learning_rate, (int, float)) else self.weights -= self.learning_rate(i + 1) * nabla

            # if (self.learning_rate, numbers.Number):
            #     self.weights -= self.learning_rate * nabla
            # else:
            #     self.weights -= self.learning_rate(i + 1) * nabla

            if self.metric:
               self.score = getattr(self, 'get_metric_score')(self.metric, y, np.dot(X, self.weights))

            if verbose and i % verbose == 0:
               if self.metric:
                   print(f'start | loss = {err} | {self.score}') if i == 0 else print(f'i = {i} | loss = {err} | {self.score}')
               else:
                   print(f'start | loss = {err}') if i == 0 else print(f'i = {i} | loss = {err}')

In [ ]:
# correct version

class MyLineReg():
    def __init__(self,
                 n_iter=3,
                 learning_rate= 0.1,
                 weights = None,
                 metric=None,
                 reg=None,
                 l1_coef: float = 0.,
                 l2_coef: float = 0.,) -> None:

        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights
        self.metric = metric
        self.reg = reg
        self.l1_coef = l1_coef
        self.l2_coef = l2_coef

    def __repr__(self):
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    def get_best_score(self):
        return self.score

    def get_coef(self):
        return self.weights[1:]

    def predict(self, X):
         X.insert(loc=0, column='x_x', value=1)

         return np.dot(X, self.weights)

    @staticmethod
    def get_metric_score(metric, y, y_pred):
        if metric == 'mae':
            score = (y - y_pred).abs().mean()
        elif metric == 'mse':
            score = np.mean((y_pred - y)**2)
        elif metric == 'rmse':
            score = np.sqrt(np.mean((y_pred - y)**2))
        elif metric == 'mape':
            score = (100 / y.shape[0]) * np.sum(abs((y - y_pred) / y))
        elif metric == 'r2':
            score = 1 - ((np.sum((y - y_pred)**2)) / (np.sum((y - np.mean(y))**2)))
        return score

    def grad(self, y_true: pd.Series, y_pred: pd.Series, X: pd.DataFrame):

        if not self.reg:
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X)
        elif self.reg == 'l1':
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X) + self.l1_coef * np.sign(self.weights)
        elif self.reg == 'l2':
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X) + self.l2_coef * 2 * (self.weights)
        elif self.reg == 'elasticnet':
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X) + self.l1_coef * np.sign(self.weights) + self.l2_coef * 2 * (self.weights)

        return grad

    def fit(self, X, y, verbose=False):
        X.insert(loc=0, column='x_0', value=1)

        self.weights = np.ones(X.shape[1])

        for i in range(self.n_iter):
            y_pred = np.dot(X, self.weights)
            err = np.mean((y_pred - y)**2)
            nabla = self.grad(y, y_pred, X)

            if isinstance(self.learning_rate, (int, float)):
                self.weights -= self.learning_rate * nabla
            else:
                self.weights -= self.learning_rate(i + 1) * nabla

            if self.metric:
               self.score = getattr(self, 'get_metric_score')(self.metric, y, np.dot(X, self.weights))

            if verbose and i % verbose == 0:
               if self.metric:
                   print(f'start | loss = {err} | {self.score} | learning_rate = {self.learning_rate}') if i == 0 else print(f'i = {i} | loss = {err} | {self.score} | learning_rate = {self.learning_rate}')
               else:
                   print(f'start | loss = {err} | learning_rate = {self.learning_rate}') if i == 0 else print(f'i = {i} | loss = {err} | learning_rate = {self.learning_rate}')

# 2_1_14


Стохастический градиентный спуск (реализация)
Добавьте в класс MyLineReg два новых параметра:

sgd_sample – кол-во образцов, которое будет использоваться на каждой итерации обучения. Может принимать либо целые числа, либо дробные от 0.0 до 1.0.
По-умолчанию: None

random_state – для воспроизводимости результата зафиксируем сид (об этом далее).
По-умолчанию: 42
Внесем изменение в алгоритм обучения:

В начале обучения фиксируем сид (см. ниже).
В начале каждого шага формируется новый мини-пакет, состоящий из случайно выбранных элементов обучающего набора. Кол-во отобранных элементов определяется параметром sgd_sample:
Если задано целое число, то из исходного датасета берется ровно столько примеров сколько указано.
Если задано дробное число, то рассматриваем его как долю от количества строк в исходном датасете (округленное до целого числа).
Расчет градиента (и последующее изменение весов) делаем на основе мини-пакета.
Все остальные параметры, если они заданы (например, регуляризация), также должны учитываться при обучении.
Ошибку и метрику необходимо считать на всем датасете, а не на мини-пакете.
Если sgd_sample = None, то обучение выполняется как раньше (на всех данных).
Случайная генерация

Т.к. у нас формальная проверка кода, то у всех должны получиться одинаковые случайные подвыборки. Поэтому и способ у всех будет одинаковый.

В начале обучения посредством модуля random фиксирум сид:

random.seed(<random_state>)
В начале каждой итерации сформируем порядковые номера строк, которые стоит отобрать.

sample_rows_idx = random.sample(range(X.shape[0]), <sgd_sample>)
В этом случае при каждом запуске будут генерироваться одни и те же номера строк. Что позволит нам добиться воспроизводимости.

З.Ы. Модуль random уже импортирован.

Тестирование

Входные данные: различные значения параметра sgd_sample
Выходные данные: коэффициенты обученной линейной регрессии (их среднее)

In [85]:
class MyLineReg():
    def __init__(self,
                 n_iter=50,
                 learning_rate= 0.1,
                 weights = None,
                 metric=None,
                 reg=None,
                 l1_coef: float = 0.,
                 l2_coef: float = 0.,
                 sgd_sample: float = None,
                 random_state: int = 42) -> None:

        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights
        self.metric = metric
        self.reg = reg
        self.l1_coef = l1_coef
        self.l2_coef = l2_coef
        self.sgd_sample = sgd_sample
        random.seed(random_state)

    def __repr__(self):
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    def get_best_score(self):
        return self.score

    def get_coef(self):
        return self.weights[1:]

    def predict(self, X):
         X.insert(loc=0, column='x_x', value=1)
         return np.dot(X, self.weights)

    def get_batch(self, x_length):
        # return random.sample(range(int(self.sgd_sample * x_length), self.sgd_sample)) if isinstance(self.sgd_sample, float) else random.sample(range(x_length), self.sgd_sample)
        if isinstance(self.sgd_sample, float):
            amount = int(self.sgd_sample * x_length)
        else:
            amount = self.sgd_sample
        return random.sample(range(x_length), amount)

    @staticmethod
    def get_metric_score(metric, y, y_pred):
        if metric == 'mae':
            score = (y - y_pred).abs().mean()
        elif metric == 'mse':
            score = np.mean((y_pred - y)**2)
        elif metric == 'rmse':
            score = np.sqrt(np.mean((y_pred - y)**2))
        elif metric == 'mape':
            score = (100 / y.shape[0]) * np.sum(abs((y - y_pred) / y))
        elif metric == 'r2':
            score = 1 - ((np.sum((y - y_pred)**2)) / (np.sum((y - np.mean(y))**2)))
        return score

    def grad(self, y_true: pd.Series, y_pred: pd.Series, X: pd.DataFrame, batch_idxs):
        y_true = y_true.iloc[batch_idxs]
        y_pred = y_pred.iloc[batch_idxs]
        X = X.iloc[batch_idxs, :]

        if not self.reg:
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X)
        elif self.reg == 'l1':
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X) + self.l1_coef * np.sign(self.weights)
        elif self.reg == 'l2':
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X) + self.l2_coef * 2 * (self.weights)
        elif self.reg == 'elasticnet':
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X) + self.l1_coef * np.sign(self.weights) + self.l2_coef * 2 * (self.weights)

        return grad

    def fit(self, X, y, verbose=False):

        X.insert(loc=0, column='x_0', value=1)

        self.weights = np.ones(X.shape[1])

        for i in range(self.n_iter):
            sample_rows_idx = self.get_batch(X.shape[0]) if self.sgd_sample else X.index
            # X_batch = X.iloc[[sample_rows_idx]]
            y_pred = np.dot(X, self.weights)
            err = np.mean((y_pred - y)**2)
            nabla = self.grad(y, y_pred, X, sample_rows_idx)

            if isinstance(self.learning_rate, (int, float)):
                self.weights -= self.learning_rate * nabla
            else:
                self.weights -= self.learning_rate(i + 1) * nabla

            if self.metric:
               self.score = getattr(self, 'get_metric_score')(self.metric, y, np.dot(X, self.weights))

            if verbose and i % verbose == 0:
               if self.metric:
                   print(f'start | loss = {err} | {self.score} | learning_rate = {self.learning_rate}') if i == 0 else print(f'i = {i} | loss = {err} | {self.score} | learning_rate = {self.learning_rate}')
               else:
                   print(f'start | loss = {err} | learning_rate = {self.learning_rate}') if i == 0 else print(f'i = {i} | loss = {err} | learning_rate = {self.learning_rate}')

In [29]:
from sklearn.datasets import make_regression

X_mk, y_mk = make_regression(n_samples=10, n_features=3, n_informative=10, noise=15, random_state=42)

In [30]:
X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)

In [32]:
X

0         1         2
0  0.767435  1.579213 -0.469474
1 -0.234153  1.523030 -0.234137
2  0.110923 -0.544383 -1.150994
3 -0.600639  0.375698 -0.291694
4 -1.913280  0.241962 -1.724918
5 -1.012831 -0.562288  0.314247
6 -0.138264  0.496714  0.647689
7 -0.463418  0.542560 -0.465730
8 -1.412304 -0.908024  1.465649
9  0.067528 -0.225776 -1.424748

In [31]:
X.iloc[[0, 1, 3]]

0         1         2
0  0.767435  1.579213 -0.469474
1 -0.234153  1.523030 -0.234137
3 -0.600639  0.375698 -0.291694

In [26]:
import random

In [34]:
random.sample(range(10), 2)

[1, 0]

In [35]:
int(0.8 * 10)

8

In [96]:
X = pd.DataFrame(X_mk)
y = pd.Series(y_mk)

class MyLineReg():
    def __init__(self,
                 n_iter=2,
                 learning_rate= 0.1,
                 weights = None,
                 metric=None,
                 reg=None,
                 l1_coef: float = 0.,
                 l2_coef: float = 0.,
                 sgd_sample: float = None,
                 random_state: int = 42) -> None:

        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights
        self.metric = metric
        self.reg = reg
        self.l1_coef = l1_coef
        self.l2_coef = l2_coef
        self.sgd_sample = sgd_sample
        random.seed(random_state)

    def __repr__(self):
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    def get_best_score(self):
        return self.score

    def get_coef(self):
        return self.weights[1:]

    def predict(self, X):
         X.insert(loc=0, column='x_x', value=1)
         return np.dot(X, self.weights)

    def get_batch(self, x_length):
        return random.sample(range(x_length), int(self.sgd_sample * x_length)) if isinstance(self.sgd_sample, float) else random.sample(range(x_length), self.sgd_sample)
        # if isinstance(self.sgd_sample, float):
        #     amount = int(self.sgd_sample * x_length)
        # else:
        #     amount = self.sgd_sample
        # return random.sample(range(x_length), amount)

    @staticmethod
    def get_metric_score(metric, y, y_pred):
        if metric == 'mae':
            score = (y - y_pred).abs().mean()
        elif metric == 'mse':
            score = np.mean((y_pred - y)**2)
        elif metric == 'rmse':
            score = np.sqrt(np.mean((y_pred - y)**2))
        elif metric == 'mape':
            score = (100 / y.shape[0]) * np.sum(abs((y - y_pred) / y))
        elif metric == 'r2':
            score = 1 - ((np.sum((y - y_pred)**2)) / (np.sum((y - np.mean(y))**2)))
        return score

    def grad(self, y: pd.Series, y_pred: np.array, X: pd.DataFrame, batch_idxs):
        print('y\n', y)
        y = y.iloc[batch_idxs]
        print('y_new\n', y)
        y_pred = y_pred[batch_idxs]
        X = X.iloc[batch_idxs]

        if not self.reg:
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X)
        elif self.reg == 'l1':
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X) + self.l1_coef * np.sign(self.weights)
        elif self.reg == 'l2':
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X) + self.l2_coef * 2 * (self.weights)
        elif self.reg == 'elasticnet':
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X) + self.l1_coef * np.sign(self.weights) + self.l2_coef * 2 * (self.weights)

        return grad

    def fit(self, X, y, verbose=False):


        X.insert(loc=0, column='x_0', value=1)

        self.weights = np.ones(X.shape[1])

        for i in range(self.n_iter):
            sample_rows_idx = self.get_batch(X.shape[0]) if self.sgd_sample else X.index
            y_pred = np.dot(X, self.weights)
            err = np.mean((y_pred - y)**2)
            nabla = self.grad(y, y_pred, X, sample_rows_idx)

            if isinstance(self.learning_rate, (int, float)):
                # print(self.learning_rate)
                # print(nabla)
                self.weights -= self.learning_rate * nabla
            else:
                self.weights -= self.learning_rate(i + 1) * nabla

            if self.metric:
               self.score = getattr(self, 'get_metric_score')(self.metric, y, np.dot(X, self.weights))

            if verbose and i % verbose == 0:
               if self.metric:
                   print(f'start | loss = {err} | {self.score} | learning_rate = {self.learning_rate}') if i == 0 else print(f'i = {i} | loss = {err} | {self.score} | learning_rate = {self.learning_rate}')
               else:
                   print(f'start | loss = {err} | learning_rate = {self.learning_rate}') if i == 0 else print(f'i = {i} | loss = {err} | learning_rate = {self.learning_rate}')


reg = MyLineReg(metric='mape', sgd_sample=0.8)
# reg = MyLineReg(metric='mape')
reg.fit(X, y, verbose=10)

y
 0    132.662648
1     90.964130
2    -43.133126
3      8.935874
4   -107.685029
5    -62.838681
6     27.800630
7     16.882855
8    -64.731691
9    -11.958869
dtype: float64
y_new
 1     90.964130
0    132.662648
4   -107.685029
9    -11.958869
6     27.800630
5    -62.838681
8    -64.731691
2    -43.133126
dtype: float64
start | loss = 4690.118351259567 | 82.23173814529274 | learning_rate = 0.1
y
 0    132.662648
1     90.964130
2    -43.133126
3      8.935874
4   -107.685029
5    -62.838681
6     27.800630
7     16.882855
8    -64.731691
9    -11.958869
dtype: float64
y_new
 8    -64.731691
1     90.964130
6     27.800630
0    132.662648
7     16.882855
5    -62.838681
9    -11.958869
4   -107.685029
dtype: float64


In [87]:
X.index

RangeIndex(start=0, stop=10, step=1)

In [ ]:
# correct version

class MyLineReg():
    def __init__(self,
                 n_iter=2,
                 learning_rate= 0.1,
                 weights = None,
                 metric=None,
                 reg=None,
                 l1_coef: float = 0.,
                 l2_coef: float = 0.,
                 sgd_sample: float = None,
                 random_state: int = 42) -> None:

        self.n_iter = n_iter
        self.learning_rate = learning_rate
        self.weights = weights
        self.metric = metric
        self.reg = reg
        self.l1_coef = l1_coef
        self.l2_coef = l2_coef
        self.sgd_sample = sgd_sample
        random.seed(random_state)

    def __repr__(self):
        return f"MyLineReg class: n_iter={self.n_iter}, learning_rate={self.learning_rate}"

    def get_best_score(self):
        return self.score

    def get_coef(self):
        return self.weights[1:]

    def predict(self, X):
         X.insert(loc=0, column='x_x', value=1)
         return np.dot(X, self.weights)

    def get_batch(self, x_length):
        return random.sample(range(x_length), int(self.sgd_sample * x_length)) if isinstance(self.sgd_sample, float) else random.sample(range(x_length), self.sgd_sample)

    @staticmethod
    def get_metric_score(metric, y, y_pred):
        if metric == 'mae':
            score = (y - y_pred).abs().mean()
        elif metric == 'mse':
            score = np.mean((y_pred - y)**2)
        elif metric == 'rmse':
            score = np.sqrt(np.mean((y_pred - y)**2))
        elif metric == 'mape':
            score = (100 / y.shape[0]) * np.sum(abs((y - y_pred) / y))
        elif metric == 'r2':
            score = 1 - ((np.sum((y - y_pred)**2)) / (np.sum((y - np.mean(y))**2)))
        return score

    def grad(self, y: pd.Series, y_pred: np.array, X: pd.DataFrame, batch_idxs):
        y = y.iloc[batch_idxs]
        y_pred = y_pred[batch_idxs]
        X = X.iloc[batch_idxs]

        if not self.reg:
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X)
        elif self.reg == 'l1':
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X) + self.l1_coef * np.sign(self.weights)
        elif self.reg == 'l2':
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X) + self.l2_coef * 2 * (self.weights)
        elif self.reg == 'elasticnet':
           grad = (2 / y.shape[0]) * ((y_pred - y)).dot(X) + self.l1_coef * np.sign(self.weights) + self.l2_coef * 2 * (self.weights)

        return grad

    def fit(self, X, y, verbose=False):
        X.insert(loc=0, column='x_0', value=1)
        self.weights = np.ones(X.shape[1])

        for i in range(self.n_iter):
            sample_rows_idx = self.get_batch(X.shape[0]) if self.sgd_sample else range(X.shape[0])
            y_pred = np.dot(X, self.weights)
            err = np.mean((y_pred - y)**2)
            nabla = self.grad(y, y_pred, X, sample_rows_idx)

            if isinstance(self.learning_rate, (int, float)):
                self.weights -= self.learning_rate * nabla
            else:
                self.weights -= self.learning_rate(i + 1) * nabla

            if self.metric:
               self.score = getattr(self, 'get_metric_score')(self.metric, y, np.dot(X, self.weights))

            if verbose and i % verbose == 0:
               if self.metric:
                   print(f'start | loss = {err} | {self.score} | learning_rate = {self.learning_rate}') if i == 0 else print(f'i = {i} | loss = {err} | {self.score} | learning_rate = {self.learning_rate}')
               else:
                   print(f'start | loss = {err} | learning_rate = {self.learning_rate}') if i == 0 else print(f'i = {i} | loss = {err} | learning_rate = {self.learning_rate}')